### ISSUE TITLE
Application Is Stopped

### ISSUE THREAD

**Issue by steff2632** [droboports/openvpn#1]
Not sure if this is still "active" but here goes nothing.

I've tried installing the .gz from [here](https://sites.google.com/a/droboports.com/www/app-repository/openvpn-2-2-2) i know its a couple version behind but I dont have a dev environment setup for cloning and compiling the version here.

in drobo dash I get application is stopped 

I've tried replacing the .ko file in the DroboApps folder with the one from the latest firmware [here](https://github.com/droboports/kernel-drobo5n/releases/tag/v3.2.27-3.3.0) I'm on firmware 3.5.10, I know I'm using ahead and that could be the problem but hoping for some light. Im using a 5N.

I've attached a log hopefully that helps
[log.txt](https://github.com/droboports/openvpn/files/288091/log.txt)

**Comment by ricardopadilha** [comment]
Try to download the ko from here: ftp://updates.drobo.com/droboapps/kernelmodules/5N/3.2.58-2/
